<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9c933fab-664a-4ecc-b692-5e8d966e3c20</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MessageLoop.Web.Common\MessageLoop.Web.Common.csproj" />
  </ItemGroup>
</Project>
