<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Authors>Daniil Dudin</Authors>
    <Company>Message Loop</Company>
    <Product>MessageLoop.Common</Product>
    <Description>Provides a set of services for managing tasks and building custom messaging protocols.</Description>
    <PackageTags>message-loop cancellation-engine channels tpl</PackageTags>
    <RepositoryType></RepositoryType>
    <PackageProjectUrl>https://github.com/dudinda/Message-Loop</PackageProjectUrl>
    <RepositoryUrl>https://github.com/dudinda/Message-Loop</RepositoryUrl>
    <Copyright>Copyright (c) 2026 Daniil Dudin</Copyright>
    <Version>1.1.0</Version>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReleaseNotes>
      -Migrated package to netstandard2.0.
    </PackageReleaseNotes>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageReference Include="System.Text.Json" Version="10.0.12" />
    <PackageReference Include="System.Threading.Channels" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt" Link="LICENSE.txt">
      <PackagePath></PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\icon.png" Link="icon.png">
      <PackagePath></PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>
</Project>
